language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rith2000/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rith2000/docker-react npm run test